//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptive.ARR.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accession
    {
        public System.Guid AccessionID { get; set; }
        public System.Guid ParticipantObjectDescriptionID { get; set; }
        public string Number { get; set; }
    
        public virtual ParticipantObjectDescription ParticipantObjectDescription { get; set; }
    }
}
