//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptive.ARR.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorElement
    {
        public ActorElement()
        {
            this.ActiveParticipants = new HashSet<ActiveParticipant>();
            this.EventIdentifications = new HashSet<EventIdentification>();
            this.EventIdentifications1 = new HashSet<EventIdentification>();
            this.ParticipantObjectIdentifications = new HashSet<ParticipantObjectIdentification>();
        }
    
        public System.Guid ActorElementID { get; set; }
        public int ActorElementTypeID { get; set; }
        public string Code { get; set; }
        public string CodeSystemName { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<ActiveParticipant> ActiveParticipants { get; set; }
        public virtual ICollection<EventIdentification> EventIdentifications { get; set; }
        public virtual ICollection<EventIdentification> EventIdentifications1 { get; set; }
        public virtual ICollection<ParticipantObjectIdentification> ParticipantObjectIdentifications { get; set; }
    }
}
