//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptive.ARR.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditSourceIdentification
    {
        public System.Guid LogID { get; set; }
        public string AuditSourceID { get; set; }
        public string AuditEnterpriseSiteID { get; set; }
        public string Code { get; set; }
        public string CodeSystemName { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ValidLog ValidLog { get; set; }
    }
}
