//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptive.ARR.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventIdentification
    {
        public System.Guid LogID { get; set; }
        public System.Guid EventID { get; set; }
        public string EventActionCode { get; set; }
        public string EventDateTime { get; set; }
        public string EventOutcomeIndicator { get; set; }
        public Nullable<System.Guid> EventTypeCodeID { get; set; }
    
        public virtual ActorElement ActorElement { get; set; }
        public virtual ActorElement ActorElement1 { get; set; }
        public virtual ValidLog ValidLog { get; set; }
    }
}
