//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptive.ARR.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogRecorder
    {
        public System.Guid LogID { get; set; }
        public string RemoteIP { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public string LogType { get; set; }
        public bool IsValid { get; set; }
    
        public virtual InvalidLog InvalidLog { get; set; }
        public virtual ValidLog ValidLog { get; set; }
    }
}
