//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptive.ARR.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectDetailElement
    {
        public System.Guid ObjectDetailElementID { get; set; }
        public System.Guid ParticipantObjectIdentificationID { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
    
        public virtual ParticipantObjectIdentification ParticipantObjectIdentification { get; set; }
    }
}
