//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptive.ARR.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectIdentifier
    {
        public System.Guid ObjectIdentifierID { get; set; }
        public Nullable<System.Guid> ParticipantObjectDescriptionID { get; set; }
        public Nullable<System.Guid> ParticipantObjectContainsStudyID { get; set; }
        public int ObjectIdentifierType { get; set; }
        public string UID { get; set; }
    
        public virtual ParticipantObjectContainsStudy ParticipantObjectContainsStudy { get; set; }
        public virtual ParticipantObjectDescription ParticipantObjectDescription { get; set; }
    }
}
