//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptive.ARR.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantObjectContainsStudy
    {
        public ParticipantObjectContainsStudy()
        {
            this.ObjectIdentifiers = new HashSet<ObjectIdentifier>();
        }
    
        public System.Guid ParticipantObjectContainsStudyID { get; set; }
        public System.Guid ParticipantObjectDescriptionID { get; set; }
    
        public virtual ICollection<ObjectIdentifier> ObjectIdentifiers { get; set; }
        public virtual ParticipantObjectDescription ParticipantObjectDescription { get; set; }
    }
}
