//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptive.ARR.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantObjectIdentification
    {
        public ParticipantObjectIdentification()
        {
            this.ObjectDetailElements = new HashSet<ObjectDetailElement>();
            this.ParticipantObjectDescriptions = new HashSet<ParticipantObjectDescription>();
        }
    
        public System.Guid ParticipantObjectIdentificationID { get; set; }
        public System.Guid LogID { get; set; }
        public string ParticipantObjectTypeCode { get; set; }
        public string ParticipantObjectTypeCodeRole { get; set; }
        public string ParticipantObjectDataLifeCycle { get; set; }
        public System.Guid ParticipantObjectIDTypeCode { get; set; }
        public string ParticipantObjectSensitivity { get; set; }
        public string ParticipantObjectID { get; set; }
        public string ParticipantObjectName { get; set; }
        public string ParticipantObjectQuery { get; set; }
    
        public virtual ActorElement ActorElement { get; set; }
        public virtual ICollection<ObjectDetailElement> ObjectDetailElements { get; set; }
        public virtual ICollection<ParticipantObjectDescription> ParticipantObjectDescriptions { get; set; }
        public virtual ValidLog ValidLog { get; set; }
    }
}
