//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptive.ARR.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }

        public Entities(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accession> Accessions { get; set; }
        public virtual DbSet<ActiveParticipant> ActiveParticipants { get; set; }
        public virtual DbSet<ActorElement> ActorElements { get; set; }
        public virtual DbSet<AuditSourceIdentification> AuditSourceIdentifications { get; set; }
        public virtual DbSet<EventIdentification> EventIdentifications { get; set; }
        public virtual DbSet<Instance> Instances { get; set; }
        public virtual DbSet<InvalidLog> InvalidLogs { get; set; }
        public virtual DbSet<LogRecorder> LogRecorders { get; set; }
        public virtual DbSet<ObjectDetailElement> ObjectDetailElements { get; set; }
        public virtual DbSet<ObjectIdentifier> ObjectIdentifiers { get; set; }
        public virtual DbSet<ParticipantObjectContainsStudy> ParticipantObjectContainsStudies { get; set; }
        public virtual DbSet<ParticipantObjectDescription> ParticipantObjectDescriptions { get; set; }
        public virtual DbSet<ParticipantObjectIdentification> ParticipantObjectIdentifications { get; set; }
        public virtual DbSet<SOPClass> SOPClasses { get; set; }
        public virtual DbSet<ValidLog> ValidLogs { get; set; }
    }
}
