//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptive.ARR.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportedEventType
    {
        public System.Guid SupportedEventTypeID { get; set; }
        public string EventTypeCode { get; set; }
        public string EventTypeDisplayName { get; set; }
    }
}
