//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptive.ARR.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidLog
    {
        public ValidLog()
        {
            this.ActiveParticipants = new HashSet<ActiveParticipant>();
            this.ParticipantObjectIdentifications = new HashSet<ParticipantObjectIdentification>();
        }
    
        public System.Guid LogID { get; set; }
        public string Pri { get; set; }
        public Nullable<int> Version { get; set; }
        public string Timestamp { get; set; }
        public string HostName { get; set; }
        public string AppName { get; set; }
        public string ProcessID { get; set; }
        public string MessageID { get; set; }
        public string StructuredData { get; set; }
        public bool IsDicomFormat { get; set; }
        public string Data { get; set; }
    
        public virtual ICollection<ActiveParticipant> ActiveParticipants { get; set; }
        public virtual AuditSourceIdentification AuditSourceIdentification { get; set; }
        public virtual EventIdentification EventIdentification { get; set; }
        public virtual LogRecorder LogRecorder { get; set; }
        public virtual ICollection<ParticipantObjectIdentification> ParticipantObjectIdentifications { get; set; }
    }
}
